/**
 * Entitas Generated Classes for breakout
 *
 * do not edit this file
 */
module breakout {
  "use strict";

  import Pool = entitas.Pool;
  import Entity = entitas.Entity;
  import Matcher = entitas.Matcher;
  import ISystem = entitas.ISystem;
  import IMatcher = entitas.IMatcher;
  import IComponent = entitas.IComponent;

  export enum CoreComponentIds {
    Position,
    Velocity,
    Resource,
    Bounds,
    Mouse,
    Score,
    Layer,
    TotalComponents
  }

  entitas.Entity.initialize(CoreComponentIds.TotalComponents, {"entities":128,"components":64});


  export class PositionComponent implements IComponent {
    public x:number;
    public y:number;
  }
  export class VelocityComponent implements IComponent {
    public x:number;
    public y:number;
  }
  export class ResourceComponent implements IComponent {
    public name:string;
  }
  export class BoundsComponent implements IComponent {
    public radius:number;
  }
  export class MouseComponent implements IComponent {
    public x:number;
    public y:number;
  }
  export class ScoreComponent implements IComponent {
    public value:number;
  }
  export class LayerComponent implements IComponent {
    public ordinal:number;
  }


  export class Pools {
    
    static _allPools:Array<Pool>;
    
    static get allPools():Array<Pool> {
      if (Pools._allPools == null) {
        Pools._allPools = [Pools.pool];
      }
      return Pools._allPools;
    }
    
    static _pool:Pool;
    
    static get pool():Pool {
      if (Pools._pool == null) {
        Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents);
        entitas.viewer.VisualDebugging.init(Pools._pool);
      }
    
      return Pools._pool;
    }
  }
}